.TH "source Directory Reference" 3 "Wed Oct 15 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBid3\&.c\fP"
.br
.ti -1c
.RI "file \fBid3\&.h\fP"
.br
.ti -1c
.RI "file \fBid3_helper\&.c\fP"
.br
.ti -1c
.RI "file \fBid3_helper\&.h\fP"
.br
.ti -1c
.RI "file \fBid3_sort\&.c\fP"
.br
.ti -1c
.RI "file \fBid3_sort\&.h\fP"
.br
.ti -1c
.RI "file \fBio\&.c\fP"
.br
.ti -1c
.RI "file \fBio\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
