.TH "ID3_frame" 3 "Wed Oct 15 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3_frame \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBid\fP [5]"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "char \fBflags\fP [2]"
.br
.ti -1c
.RI "char \fBencoding\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ID3 Frame struct 
.PP
Definition at line 84 of file id3\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char* ID3_frame::data"

.PP
Definition at line 89 of file id3\&.c\&.
.SS "char ID3_frame::encoding"

.PP
Definition at line 88 of file id3\&.c\&.
.SS "char ID3_frame::flags[2]"

.PP
Definition at line 87 of file id3\&.c\&.
.SS "char ID3_frame::id[5]"

.PP
Definition at line 85 of file id3\&.c\&.
.SS "int ID3_frame::size"

.PP
Definition at line 86 of file id3\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ID3 Sort from the source code\&.
