.TH "ID3_file" 3 "Wed Oct 15 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3_file \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.ti -1c
.RI "\fBID3_header\fP * \fBheader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file id3\&.c\&.
.SH "Field Documentation"
.PP 
.SS "FILE* ID3_file::file"

.PP
Definition at line 187 of file id3\&.c\&.
.SS "\fBID3_header\fP* ID3_file::header"

.PP
Definition at line 188 of file id3\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ID3 Sort from the source code\&.
