.TH "ID3_header" 3 "Wed Oct 15 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3_header \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBversion\fP [2]"
.br
.ti -1c
.RI "char \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ID3 Header struct 
.PP
Definition at line 27 of file id3\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char ID3_header::flags"

.PP
Definition at line 29 of file id3\&.c\&.
.SS "uint32_t ID3_header::size"

.PP
Definition at line 30 of file id3\&.c\&.
.SS "char ID3_header::version[2]"

.PP
Definition at line 28 of file id3\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ID3 Sort from the source code\&.
