.TH "ID3_info" 3 "Fri Nov 14 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID3_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <id3_helper\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "char * \fBartist\fP"
.br
.ti -1c
.RI "char * \fBalbum\fP"
.br
.ti -1c
.RI "char * \fBtrack\fP"
.br
.ti -1c
.RI "char * \fBgenre\fP"
.br
.ti -1c
.RI "char * \fByear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file id3_helper\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* ID3_info::album"

.PP
Definition at line 8 of file id3_helper\&.h\&.
.SS "char* ID3_info::artist"

.PP
Definition at line 7 of file id3_helper\&.h\&.
.SS "char* ID3_info::genre"

.PP
Definition at line 10 of file id3_helper\&.h\&.
.SS "char* ID3_info::title"

.PP
Definition at line 6 of file id3_helper\&.h\&.
.SS "char* ID3_info::track"

.PP
Definition at line 9 of file id3_helper\&.h\&.
.SS "char* ID3_info::year"

.PP
Definition at line 11 of file id3_helper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ID3 Sort from the source code\&.
