.TH "source/io.h" 3 "Wed Oct 15 2014" "Version 1.0" "ID3 Sort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/io.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBIO_directory_exist\fP (const char *directory)"
.br
.RI "\fICheck if directory exists\&. \fP"
.ti -1c
.RI "bool \fBIO_directory_create\fP (const char *directory)"
.br
.RI "\fICreate a new directory\&. \fP"
.ti -1c
.RI "bool \fBIO_directory_remove\fP (const char *directory)"
.br
.RI "\fIRemove a directory\&. \fP"
.ti -1c
.RI "size_t \fBIO_file_size\fP (const char *filename)"
.br
.RI "\fIGet size of file in bytes\&. \fP"
.ti -1c
.RI "bool \fBIO_file_exist\fP (const char *filename)"
.br
.RI "\fICheck if file exists\&. \fP"
.ti -1c
.RI "bool \fBIO_file_copy\fP (const char *source, const char *destination)"
.br
.RI "\fICopy file from source to destination\&. \fP"
.ti -1c
.RI "bool \fBIO_file_move\fP (const char *source, const char *destination)"
.br
.RI "\fIMove file from source to destination\&. \fP"
.ti -1c
.RI "bool \fBIO_file_remove\fP (const char *filename)"
.br
.RI "\fIRemove file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool IO_directory_create (const char *directory)"

.PP
Create a new directory\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdirectory\fP Path to the directory 
.RE
.PP
\fBReturns:\fP
.RS 4
true if directory could be created, false otherwise 
.RE
.PP

.PP
Definition at line 19 of file io\&.c\&.
.SS "bool IO_directory_exist (const char *directory)"

.PP
Check if directory exists\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdirectory\fP Path to the directory 
.RE
.PP
\fBReturns:\fP
.RS 4
true if directory exist, false otherwise 
.RE
.PP

.PP
Definition at line 9 of file io\&.c\&.
.SS "bool IO_directory_remove (const char *directory)"

.PP
Remove a directory\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdirectory\fP Path to the directory 
.RE
.PP
\fBReturns:\fP
.RS 4
true if directory could be removed, false otherwise 
.RE
.PP

.PP
Definition at line 27 of file io\&.c\&.
.SS "bool IO_file_copy (const char *source, const char *destination)"

.PP
Copy file from source to destination\&. 
.PP
\fBWarning:\fP
.RS 4
This function has not been implemented yet
.RE
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP Path to the file to be copied 
.br
\fIdestination\fP Path to copy to\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true if file could be copied, false otherwise 
.RE
.PP

.PP
Definition at line 59 of file io\&.c\&.
.SS "bool IO_file_exist (const char *filename)"

.PP
Check if file exists\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Path to the file 
.RE
.PP
\fBReturns:\fP
.RS 4
true if file exist, false otherwise 
.RE
.PP

.PP
Definition at line 49 of file io\&.c\&.
.SS "bool IO_file_move (const char *source, const char *destination)"

.PP
Move file from source to destination\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP Path to the file being moved 
.br
\fIdestination\fP Path where the file should be moved 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the file could be moved, false otherwise 
.RE
.PP

.PP
Definition at line 85 of file io\&.c\&.
.SS "bool IO_file_remove (const char *filename)"

.PP
Remove file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Path to the file to be removed 
.RE
.PP
\fBReturns:\fP
.RS 4
bool if file could be removed, false otherwise 
.RE
.PP

.PP
Definition at line 93 of file io\&.c\&.
.SS "size_t IO_file_size (const char *filename)"

.PP
Get size of file in bytes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP Path to the file 
.RE
.PP
\fBReturns:\fP
.RS 4
size of the file in bytes, -1 if file doesn't exist or couldn't be opened 
.RE
.PP

.PP
Definition at line 36 of file io\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ID3 Sort from the source code\&.
